# Generated by Django 3.1.2 on 2021-12-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211214_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
