# Generated by Django 3.1.2 on 2021-12-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211214_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='documento',
        ),
    ]
