# Generated by Django 3.1.2 on 2021-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tarea_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='documento',
            field=models.ImageField(null=True, upload_to='tareas'),
        ),
    ]
