# Generated by Django 3.1.2 on 2021-12-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tarea_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='documento',
            field=models.FileField(null=True, upload_to='tareas'),
        ),
    ]
