# Generated by Django 3.1.2 on 2021-12-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211215_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='documento',
        ),
    ]
