# Generated by Django 3.1.2 on 2021-12-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_tarea_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proyecto'),
        ),
    ]
